import fs from 'fs'
import path from 'path'
import { Router, Request, Response, NextFunction } from 'express'
import { v4 as uuidv4 } from 'uuid'
import type { AnalyticsOpts } from './types'
import type { ProjectRegistry, ProjectContext } from './project-registry'
import {
  listJobs, getJob, getJobEvents, purgeJobs, deleteJob, getProjectActivity,
  createConversation, listConversations, getConversation,
  deleteConversation, updateConversation, getMessages,
  getStats, getPipelineJobs,
  createProposal, getProposal, listProposals, deleteProposal,
  createTemplate, listTemplates, getTemplate, updateTemplate, deleteTemplate,
  getProjectSettings, updateProjectSettings,
  getTelemetryBlob, getTelemetrySummaries, getJobsWithTelemetry, hasJobTelemetry,
} from './db'
import { createDiagnosticZip } from './telemetry-export'
import { getProjectSetupSession } from './hub-db'
import { ClaudeNotFoundError, JobNotFoundError, JobAlreadyTerminalError, DEFAULT_ZOMBIE_TIMEOUT_MS } from './queue-manager'
import type { JobPriority } from './types'
import { VALID_PRIORITIES } from './types'
import { resolveCommand } from './command-resolver'
import { createHooksRouter, getPhaseStates } from './hooks'
import { getConfig, fetchIssues } from './config'
import { getAnalytics, getTrends } from './analytics'
import type { ChatConversationRow, TrendsPeriod, JobTemplate, JobRow } from './types'
import { readChanges } from './changes-reader'
import { getProjectMetrics } from './metrics'
import {
  resolveTicketStoragePath, readStore, mutateStore, filterTickets,
  isValidStatus, isValidPriority,
  type Ticket,
} from './ticket-store'
import type { TicketCreatedMessage, TicketUpdatedMessage, TicketDeletedMessage, TicketAiEditStreamMessage, TicketAiEditDoneMessage, TicketAiEditErrorMessage, SpecGenStreamMessage, SpecGenDoneMessage, SpecGenErrorMessage, LocalTicket } from './types'
import { spawn } from 'child_process'
import { createInterface } from 'readline'
import treeKill from 'tree-kill'
import multer from 'multer'
import { createRailsRouter } from './rails-router'
import { attachmentManager, SUPPORTED_MIME_TYPES, USER_ATTACHMENT_SYSTEM_NOTE } from './attachment-manager'
import {
  getTerminalManager,
  TerminalLimitExceededError,
  TerminalNotFoundError,
  TerminalNameInvalidError,
  TERMINAL_MAX_PER_PROJECT,
} from './terminal-manager'

const TERMINAL_PANEL_ENABLED = process.env.SPECRAILS_TERMINAL_PANEL !== 'false'

// ─── YAML helpers ─────────────────────────────────────────────────────────────

/**
 * Serialize install config to YAML matching specrails-core's tui-installer format exactly.
 */
function serializeInstallConfigYaml(config: Record<string, unknown>): string {
  const c = config as {
    version?: number
    provider?: string
    tier?: string
    agents?: { selected?: string[]; excluded?: string[] }
    models?: { preset?: string; defaults?: { model?: string }; overrides?: Record<string, string> }
    agent_teams?: boolean
  }

  const overrides = c.models?.overrides ?? {}
  const overridesEntries = Object.entries(overrides)
  const overridesYaml = overridesEntries.length > 0
    ? '\n' + overridesEntries.map(([k, v]) => `    ${k}: ${v}`).join('\n')
    : ' {}'

  const lines = [
    '# specrails install config — generated by specrails-hub',
    '# Re-run: npx specrails-core@latest init  to regenerate',
    `version: ${c.version ?? 1}`,
    `provider: ${c.provider ?? 'claude'}`,
    `tier: ${c.tier ?? 'quick'}`,
    `agents:`,
    `  selected: [${(c.agents?.selected ?? []).join(', ')}]`,
    `  excluded: [${(c.agents?.excluded ?? []).join(', ')}]`,
    `models:`,
    `  preset: ${c.models?.preset ?? 'balanced'}`,
    `  defaults: { model: ${c.models?.defaults?.model ?? 'sonnet'} }`,
    `  overrides:${overridesYaml}`,
    `agent_teams: ${c.agent_teams ?? false}`,
    '',
  ]

  return lines.join('\n')
}

// ─── Agent model helpers ──────────────────────────────────────────────────────

const VALID_MODEL_ALIASES = ['sonnet', 'opus', 'haiku'] as const
type ModelAlias = typeof VALID_MODEL_ALIASES[number]

/**
 * Read installed agents from `.claude/agents/*.md` (top-level only, no subdirs).
 * Extracts the `model:` field from YAML frontmatter.
 */
function readAgentModels(projectPath: string): { name: string; model: string }[] {
  const agentsDir = path.join(projectPath, '.claude', 'agents')
  if (!fs.existsSync(agentsDir)) return []

  let entries: string[]
  try {
    entries = fs.readdirSync(agentsDir)
  } catch {
    return []
  }

  const agents: { name: string; model: string }[] = []
  for (const entry of entries) {
    // Top-level .md files only — skip subdirs
    if (!entry.endsWith('.md')) continue
    const filePath = path.join(agentsDir, entry)
    try {
      const stat = fs.statSync(filePath)
      if (!stat.isFile()) continue
      const content = fs.readFileSync(filePath, 'utf-8')
      // Extract model from YAML frontmatter between --- markers
      const frontmatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/)
      if (!frontmatterMatch) continue
      const frontmatter = frontmatterMatch[1]
      const modelMatch = frontmatter.match(/^model:\s*(.+)$/m)
      const model = modelMatch ? modelMatch[1].trim() : 'sonnet'
      agents.push({ name: entry.slice(0, -3), model })
    } catch {
      // skip unreadable files
    }
  }
  return agents
}

/**
 * Read `.specrails/install-config.yaml` and patch the `model:` line in each
 * `.claude/agents/*.md` frontmatter to match the config's defaults/overrides.
 * No-op if the config file does not exist.
 */
function applyModelConfig(projectPath: string): void {
  const configPath = path.join(projectPath, '.specrails', 'install-config.yaml')
  if (!fs.existsSync(configPath)) return

  let configText: string
  try {
    configText = fs.readFileSync(configPath, 'utf-8')
  } catch {
    return
  }

  // Parse defaults.model
  const defaultsMatch = configText.match(/defaults:\s*\{\s*model:\s*(\S+)\s*\}/)
  const defaultModel: string = defaultsMatch ? defaultsMatch[1] : 'sonnet'

  // Parse overrides block — lines like `    agentname: alias`
  const overrides: Record<string, string> = {}
  const overridesBlockMatch = configText.match(/overrides:([\s\S]*?)(?:\n\S|$)/)
  if (overridesBlockMatch) {
    const block = overridesBlockMatch[1]
    const overrideLines = block.match(/^ {2,}(\S+):\s*(\S+)/gm) ?? []
    for (const line of overrideLines) {
      const m = line.match(/^\s+(\S+):\s*(\S+)/)
      if (m) overrides[m[1]] = m[2]
    }
  }

  const agentsDir = path.join(projectPath, '.claude', 'agents')
  if (!fs.existsSync(agentsDir)) return

  let entries: string[]
  try {
    entries = fs.readdirSync(agentsDir)
  } catch {
    return
  }

  for (const entry of entries) {
    if (!entry.endsWith('.md')) continue
    const filePath = path.join(agentsDir, entry)
    try {
      const stat = fs.statSync(filePath)
      if (!stat.isFile()) continue
      const agentName = entry.slice(0, -3)
      const targetModel = overrides[agentName] ?? defaultModel
      const content = fs.readFileSync(filePath, 'utf-8')
      const patched = content.replace(/^model: .+$/m, `model: ${targetModel}`)
      if (patched !== content) {
        fs.writeFileSync(filePath, patched, 'utf-8')
      }
    } catch {
      // skip unwritable files
    }
  }
}

// Extend Express Request to carry resolved ProjectContext
declare module 'express-serve-static-core' {
  interface Request {
    projectCtx?: ProjectContext
  }
}

export function createProjectRouter(registry: ProjectRegistry): Router {
  const router = Router({ mergeParams: true })

  // Middleware: resolve project from :projectId param
  router.use('/:projectId', (req: Request, res: Response, next: NextFunction) => {
    const projectId = req.params.projectId as string
    const ctx = registry.getContext(projectId)
    if (!ctx) {
      res.status(404).json({ error: 'Project not found' })
      return
    }
    registry.touchProject(projectId)
    req.projectCtx = ctx
    next()
  })

  // Helper to get ctx (always defined after middleware)
  function ctx(req: Request): ProjectContext {
    return req.projectCtx!
  }

  // ─── Hooks ──────────────────────────────────────────────────────────────────

  // Mount hooks router under each project
  router.use('/:projectId/hooks', (req: Request, res: Response, next: NextFunction) => {
    const projectCtx = ctx(req)
    const hooksRouter = createHooksRouter(
      projectCtx.broadcast,
      projectCtx.db,
      {
        get current() { return projectCtx.queueManager.getActiveJobId() },
        set current(_: string | null) { /* managed by QueueManager */ },
      }
    )
    hooksRouter(req, res, next)
  })

  // Mount rails router under each project
  const railsRouter = createRailsRouter()
  router.use('/:projectId/rails', railsRouter)

  // ─── Queue / Spawn routes ────────────────────────────────────────────────────

  router.post('/:projectId/spawn', (req: Request, res: Response) => {
    const { command, priority, dependsOnJobId, pipelineId } = req.body ?? {}
    if (!command || typeof command !== 'string' || !command.trim()) {
      res.status(400).json({ error: 'command is required' })
      return
    }
    if (priority !== undefined && !VALID_PRIORITIES.has(priority)) {
      res.status(400).json({ error: 'priority must be one of: low, normal, high, critical' })
      return
    }
    try {
      const job = ctx(req).queueManager.enqueue(command, (priority as JobPriority) ?? 'normal', {
        dependsOnJobId: dependsOnJobId || undefined,
        pipelineId: pipelineId || undefined,
      })
      const position = job.queuePosition ?? 0
      res.status(202).json({ jobId: job.id, position })
    } catch (err) {
      if (err instanceof ClaudeNotFoundError) {
        res.status(400).json({ error: err.message })
      } else {
        console.error('[project-router] spawn error:', err)
        res.status(500).json({ error: 'Internal server error' })
      }
    }
  })

  // ─── Pipeline routes ──────────────────────────────────────────────────────────
  // NOTE: Ad-hoc pipeline creation removed — use rails (templates) instead.
  // The GET route remains for viewing existing pipeline status.

  router.get('/:projectId/pipelines/:pipelineId', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const pipelineId = req.params.pipelineId as string
    const jobs = getPipelineJobs(db, pipelineId)
    if (jobs.length === 0) {
      res.status(404).json({ error: 'Pipeline not found' })
      return
    }
    const allCompleted = jobs.every(j => j.status === 'completed')
    const anyFailed = jobs.some(j => ['failed', 'skipped', 'canceled', 'zombie_terminated'].includes(j.status))
    const status = allCompleted ? 'completed' : anyFailed ? 'failed' : 'running'
    res.json({ pipelineId, status, jobs })
  })

  router.get('/:projectId/state', (req: Request, res: Response) => {
    const { queueManager, project } = ctx(req)
    res.json({
      projectName: project.name,
      projectId: project.id,
      phases: getPhaseStates(),
      busy: queueManager.getActiveJobId() !== null,
      currentJobId: queueManager.getActiveJobId(),
    })
  })

  router.delete('/:projectId/jobs/:id', (req: Request, res: Response) => {
    try {
      const result = ctx(req).queueManager.cancel(req.params.id as string)
      res.json({ ok: true, status: result })
    } catch (err) {
      if (err instanceof JobNotFoundError) {
        res.status(404).json({ error: 'Job not found' })
      } else if (err instanceof JobAlreadyTerminalError) {
        // Job already finished — delete it from the DB
        deleteJob(ctx(req).db, req.params.id as string)
        res.json({ ok: true, status: 'deleted' })
      } else {
        res.status(500).json({ error: 'Internal server error' })
      }
    }
  })

  router.patch('/:projectId/jobs/:id/priority', (req: Request, res: Response) => {
    const { priority } = req.body ?? {}
    if (!priority || !VALID_PRIORITIES.has(priority)) {
      res.status(400).json({ error: 'priority must be one of: low, normal, high, critical' })
      return
    }
    try {
      ctx(req).queueManager.updatePriority(req.params.id as string, priority as JobPriority)
      res.json({ ok: true })
    } catch (err) {
      if (err instanceof JobNotFoundError) {
        res.status(404).json({ error: 'Job not found' })
      } else {
        res.status(400).json({ error: (err as Error).message })
      }
    }
  })

  router.post('/:projectId/queue/pause', (req: Request, res: Response) => {
    ctx(req).queueManager.pause()
    res.json({ ok: true, paused: true })
  })

  router.post('/:projectId/queue/resume', (req: Request, res: Response) => {
    ctx(req).queueManager.resume()
    res.json({ ok: true, paused: false })
  })

  router.put('/:projectId/queue/reorder', (req: Request, res: Response) => {
    const { jobIds } = req.body ?? {}
    if (!Array.isArray(jobIds)) {
      res.status(400).json({ error: 'jobIds must be an array' })
      return
    }
    try {
      ctx(req).queueManager.reorder(jobIds)
      res.json({ ok: true, queue: jobIds })
    } catch (err) {
      res.status(400).json({ error: (err as Error).message })
    }
  })

  router.get('/:projectId/queue', (req: Request, res: Response) => {
    const { queueManager } = ctx(req)
    res.json({
      jobs: queueManager.getJobs(),
      paused: queueManager.isPaused(),
      activeJobId: queueManager.getActiveJobId(),
    })
  })

  router.get('/:projectId/jobs', (req: Request, res: Response) => {
    const limit = Math.min(parseInt(String(req.query.limit ?? '50'), 10) || 50, 200)
    const offset = parseInt(String(req.query.offset ?? '0'), 10) || 0
    const status = req.query.status as string | undefined
    const from = req.query.from as string | undefined
    const to = req.query.to as string | undefined
    const { db } = ctx(req)
    const result = listJobs(db, { limit, offset, status, from, to })

    // Merge in-memory queued jobs that haven't been persisted to DB yet
    const { queueManager } = ctx(req)
    const dbIds = new Set(result.jobs.map((j) => j.id))
    const queuedRows = queueManager
      .getJobs()
      .filter((j) => j.status === 'queued' && !dbIds.has(j.id))
      .filter((j) => !status || j.status === status)
      .map((j) => ({
        id: j.id,
        command: j.command,
        started_at: j.startedAt ?? new Date().toISOString(),
        finished_at: j.finishedAt,
        status: j.status,
        exit_code: j.exitCode,
        queue_position: j.queuePosition,
        priority: j.priority,
        tokens_in: null,
        tokens_out: null,
        tokens_cache_read: null,
        tokens_cache_create: null,
        total_cost_usd: null,
        num_turns: null,
        model: null,
        duration_ms: null,
        duration_api_ms: null,
        session_id: null,
        depends_on_job_id: j.dependsOnJobId,
        pipeline_id: j.pipelineId,
        skip_reason: j.skipReason,
      } as import('./types').JobRow))

    if (queuedRows.length > 0) {
      result.jobs = [...queuedRows, ...result.jobs]
      result.total += queuedRows.length
    }

    // Annotate each job with hasTelemetry so the client can show the
    // Export diagnostic button without an extra round trip.
    const jobsWithTelemetry = getJobsWithTelemetry(db)
    const annotatedJobs = result.jobs.map((j) => ({
      ...j,
      hasTelemetry: jobsWithTelemetry.has(j.id),
    }))

    res.json({ jobs: annotatedJobs, total: result.total })
  })

  // ─── CSV helper ──────────────────────────────────────────────────────────────
  const toCsv = (headers: string[], rows: Record<string, unknown>[]): string => {
    const escape = (v: unknown) => {
      const s = v == null ? '' : String(v)
      return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s
    }
    const lines = [headers.join(',')]
    for (const row of rows) {
      lines.push(headers.map(h => escape(row[h])).join(','))
    }
    return lines.join('\n')
  }

  // ─── Jobs export (must be before /:projectId/jobs/:id) ─────────────────────
  router.get('/:projectId/jobs/export', (req: Request, res: Response) => {
    const format = (req.query.format as string) || 'json'
    if (format !== 'json' && format !== 'csv') {
      res.status(400).json({ error: 'Invalid format. Must be json or csv' })
      return
    }
    const from = req.query.from as string | undefined
    const to = req.query.to as string | undefined
    const { db } = ctx(req)
    const conditions: string[] = []
    const params: unknown[] = []
    if (from) { conditions.push('started_at >= ?'); params.push(from) }
    if (to) { conditions.push('started_at <= ?'); params.push(to) }
    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : ''
    const jobs = db
      .prepare(`SELECT * FROM jobs ${where} ORDER BY started_at DESC LIMIT 10000`)
      .all(...params) as JobRow[]
    if (format === 'csv') {
      const headers = ['id', 'command', 'status', 'started_at', 'finished_at', 'duration_ms', 'tokens_in', 'tokens_out', 'tokens_cache_read', 'total_cost_usd', 'model']
      const csv = toCsv(headers, jobs as unknown as Record<string, unknown>[])
      res.setHeader('Content-Type', 'text/csv')
      res.setHeader('Content-Disposition', 'attachment; filename="jobs-export.csv"')
      res.send(csv)
    } else {
      res.json({ jobs })
    }
  })

  router.get('/:projectId/jobs/:id', (req: Request, res: Response) => {
    const { db, queueManager } = ctx(req)
    const job = getJob(db, req.params.id as string)
    if (!job) { res.status(404).json({ error: 'Job not found' }); return }
    const events = getJobEvents(db, req.params.id as string)
    const phaseDefinitions = queueManager.phasesForCommand(job.command)
    const annotated = { ...job, hasTelemetry: hasJobTelemetry(db, req.params.id as string) }
    res.json({ job: annotated, events, phaseDefinitions })
  })

  router.delete('/:projectId/jobs', (req: Request, res: Response) => {
    try {
      const { from, to } = req.body ?? {}
      const deleted = purgeJobs(ctx(req).db, { from, to })
      res.json({ ok: true, deleted })
    } catch (err) {
      console.error('[project-router] purge error:', err)
      res.status(500).json({ error: 'Failed to purge jobs' })
    }
  })

  router.get('/:projectId/activity', (req: Request, res: Response) => {
    const limit = Math.min(
      Math.max(1, parseInt(String(req.query.limit ?? '50'), 10) || 50),
      100
    )
    const before = req.query.before as string | undefined
    res.json(getProjectActivity(ctx(req).db, { limit, before }))
  })

  router.get('/:projectId/stats', (req: Request, res: Response) => {
    res.json(getStats(ctx(req).db))
  })

  router.get('/:projectId/metrics', (req: Request, res: Response) => {
    const { project, db } = ctx(req)
    try {
      res.json(getProjectMetrics(project.path, db))
    } catch (err) {
      console.error('[project-router] metrics error:', err)
      res.status(500).json({ error: 'Failed to compute metrics' })
    }
  })

  router.get('/:projectId/analytics', (req: Request, res: Response) => {
    const period = (req.query.period as string) || '7d'
    const from = req.query.from as string | undefined
    const to = req.query.to as string | undefined
    const validPeriods = ['7d', '30d', '90d', 'all', 'custom']
    if (!validPeriods.includes(period)) {
      res.status(400).json({ error: 'Invalid period. Must be one of: 7d, 30d, 90d, all, custom' })
      return
    }
    if (period === 'custom' && (!from || !to)) {
      res.status(400).json({ error: 'from and to are required for custom period' })
      return
    }
    try {
      res.json(getAnalytics(ctx(req).db, { period: period as AnalyticsOpts['period'], from, to }))
    } catch (err) {
      console.error('[project-router] analytics error:', err)
      res.status(500).json({ error: 'Failed to compute analytics' })
    }
  })

  // ─── Analytics export ────────────────────────────────────────────────────────
  router.get('/:projectId/analytics/export', (req: Request, res: Response) => {
    const format = (req.query.format as string) || 'json'
    if (format !== 'json' && format !== 'csv') {
      res.status(400).json({ error: 'Invalid format. Must be json or csv' })
      return
    }
    const period = (req.query.period as string) || '7d'
    const from = req.query.from as string | undefined
    const to = req.query.to as string | undefined
    const validPeriods = ['7d', '30d', '90d', 'all', 'custom']
    if (!validPeriods.includes(period)) {
      res.status(400).json({ error: 'Invalid period. Must be one of: 7d, 30d, 90d, all, custom' })
      return
    }
    if (period === 'custom' && (!from || !to)) {
      res.status(400).json({ error: 'from and to are required for custom period' })
      return
    }
    try {
      const analytics = getAnalytics(ctx(req).db, { period: period as AnalyticsOpts['period'], from, to })
      if (format === 'csv') {
        const headers = ['command', 'totalRuns', 'successRate', 'avgCostUsd', 'avgDurationMs', 'totalCostUsd']
        const csv = toCsv(headers, analytics.commandPerformance as unknown as Record<string, unknown>[])
        res.setHeader('Content-Type', 'text/csv')
        res.setHeader('Content-Disposition', 'attachment; filename="analytics-export.csv"')
        res.send(csv)
      } else {
        res.json(analytics)
      }
    } catch (err) {
      console.error('[project-router] analytics export error:', err)
      res.status(500).json({ error: 'Failed to compute analytics' })
    }
  })

  router.get('/:projectId/trends', (req: Request, res: Response) => {
    const period = (req.query.period as string) || '7d'
    const validPeriods: TrendsPeriod[] = ['1d', '7d', '30d']
    if (!validPeriods.includes(period as TrendsPeriod)) {
      res.status(400).json({ error: 'Invalid period. Must be one of: 1d, 7d, 30d' })
      return
    }
    try {
      res.json(getTrends(ctx(req).db, period as TrendsPeriod))
    } catch (err) {
      console.error('[project-router] trends error:', err)
      res.status(500).json({ error: 'Failed to compute trends' })
    }
  })

  router.get('/:projectId/jobs/compare', (req: Request, res: Response) => {
    const raw = req.query.jobIds as string | undefined
    if (!raw) {
      res.status(400).json({ error: 'jobIds query param required (comma-separated, exactly 2)' })
      return
    }
    const ids = raw.split(',').map((s) => s.trim()).filter(Boolean)
    if (ids.length !== 2) {
      res.status(400).json({ error: 'Exactly 2 jobIds are required' })
      return
    }
    const { db } = ctx(req)
    const rows = ids.map((id) => {
      const job = db.prepare('SELECT * FROM jobs WHERE id = ?').get(id) as {
        id: string; command: string; status: string; started_at: string; finished_at: string | null
        duration_ms: number | null; tokens_in: number | null; tokens_out: number | null
        tokens_cache_read: number | null; total_cost_usd: number | null; model: string | null
      } | undefined
      if (!job) return null
      const phases = db.prepare(
        "SELECT phase FROM job_phases WHERE job_id = ? AND state = 'done' ORDER BY updated_at ASC"
      ).all(id) as Array<{ phase: string }>
      return {
        id: job.id,
        command: job.command,
        status: job.status,
        startedAt: job.started_at,
        finishedAt: job.finished_at,
        durationMs: job.duration_ms,
        tokensIn: job.tokens_in,
        tokensOut: job.tokens_out,
        tokensCacheRead: job.tokens_cache_read,
        totalCostUsd: job.total_cost_usd,
        model: job.model,
        phasesCompleted: phases.map((p) => p.phase),
      }
    })
    const missing = ids.filter((_, i) => rows[i] === null)
    if (missing.length > 0) {
      res.status(404).json({ error: `Jobs not found: ${missing.join(', ')}` })
      return
    }
    res.json({ jobs: rows })
  })

  router.get('/:projectId/config', (req: Request, res: Response) => {
    const { project, db } = ctx(req)
    try {
      const config = getConfig(project.path, db, project.name)
      const dailyBudgetRaw = (db.prepare(`SELECT value FROM queue_state WHERE key = 'config.daily_budget_usd'`).get() as { value: string } | undefined)?.value
      const dailyBudgetUsd = dailyBudgetRaw != null ? parseFloat(dailyBudgetRaw) : null
      const zombieTimeoutRaw = (db.prepare(`SELECT value FROM queue_state WHERE key = 'config.zombie_timeout_ms'`).get() as { value: string } | undefined)?.value
      const zombieTimeoutMs = zombieTimeoutRaw != null ? parseInt(zombieTimeoutRaw, 10) : null
      res.json({ ...config, dailyBudgetUsd, zombieTimeoutMs })
    } catch (err) {
      console.error('[project-router] config error:', err)
      res.status(500).json({ error: 'Failed to read config' })
    }
  })

  router.post('/:projectId/config', (req: Request, res: Response) => {
    const { active, labelFilter, dailyBudgetUsd, zombieTimeoutMs } = req.body ?? {}
    const { db, queueManager } = ctx(req)
    try {
      if (active !== undefined) {
        db.prepare(`INSERT OR REPLACE INTO queue_state (key, value) VALUES ('config.active_tracker', ?)`).run(active ?? '')
      }
      if (labelFilter !== undefined) {
        db.prepare(`INSERT OR REPLACE INTO queue_state (key, value) VALUES ('config.label_filter', ?)`).run(labelFilter ?? '')
      }
      if (dailyBudgetUsd !== undefined) {
        if (dailyBudgetUsd === null) {
          db.prepare(`DELETE FROM queue_state WHERE key = 'config.daily_budget_usd'`).run()
        } else if (typeof dailyBudgetUsd === 'number' && dailyBudgetUsd > 0) {
          db.prepare(`INSERT OR REPLACE INTO queue_state (key, value) VALUES ('config.daily_budget_usd', ?)`).run(String(dailyBudgetUsd))
        }
      }
      if (zombieTimeoutMs !== undefined) {
        if (zombieTimeoutMs === null) {
          db.prepare(`DELETE FROM queue_state WHERE key = 'config.zombie_timeout_ms'`).run()
        } else if (typeof zombieTimeoutMs === 'number' && zombieTimeoutMs > 0) {
          db.prepare(`INSERT OR REPLACE INTO queue_state (key, value) VALUES ('config.zombie_timeout_ms', ?)`).run(String(zombieTimeoutMs))
        }
        queueManager.setZombieTimeout(typeof zombieTimeoutMs === 'number' && zombieTimeoutMs > 0 ? zombieTimeoutMs : DEFAULT_ZOMBIE_TIMEOUT_MS)
      }
      res.json({ ok: true })
    } catch (err) {
      console.error('[project-router] config persist error:', err)
      res.status(500).json({ error: 'Failed to persist config' })
    }
  })

  // ─── Budget routes ────────────────────────────────────────────────────────────

  router.get('/:projectId/budget', (req: Request, res: Response) => {
    const { db } = ctx(req)
    try {
      const dailyBudgetRaw = (db.prepare(`SELECT value FROM queue_state WHERE key = 'config.daily_budget_usd'`).get() as { value: string } | undefined)?.value
      const dailyBudgetUsd = dailyBudgetRaw != null ? parseFloat(dailyBudgetRaw) : null
      const jobThresholdRaw = (db.prepare(`SELECT value FROM queue_state WHERE key = 'config.job_cost_threshold_usd'`).get() as { value: string } | undefined)?.value
      const jobCostThresholdUsd = jobThresholdRaw != null ? parseFloat(jobThresholdRaw) : null
      const costRow = db.prepare(
        `SELECT COALESCE(SUM(total_cost_usd), 0) as costToday FROM jobs WHERE started_at >= date('now')`
      ).get() as { costToday: number }
      const costToday = costRow.costToday
      const budgetUtilizationPct = dailyBudgetUsd != null && dailyBudgetUsd > 0
        ? (costToday / dailyBudgetUsd) * 100
        : null
      res.json({ dailyBudgetUsd, jobCostThresholdUsd, costToday, budgetUtilizationPct })
    } catch (err) {
      console.error('[project-router] budget get error:', err)
      res.status(500).json({ error: 'Failed to read budget' })
    }
  })

  router.patch('/:projectId/budget', (req: Request, res: Response) => {
    const { dailyBudgetUsd, jobCostThresholdUsd } = req.body ?? {}
    const { db } = ctx(req)
    try {
      if (dailyBudgetUsd !== undefined) {
        if (dailyBudgetUsd === null) {
          db.prepare(`DELETE FROM queue_state WHERE key = 'config.daily_budget_usd'`).run()
        } else if (typeof dailyBudgetUsd === 'number' && dailyBudgetUsd > 0) {
          db.prepare(`INSERT OR REPLACE INTO queue_state (key, value) VALUES ('config.daily_budget_usd', ?)`).run(String(dailyBudgetUsd))
        }
      }
      if (jobCostThresholdUsd !== undefined) {
        if (jobCostThresholdUsd === null) {
          db.prepare(`DELETE FROM queue_state WHERE key = 'config.job_cost_threshold_usd'`).run()
        } else if (typeof jobCostThresholdUsd === 'number' && jobCostThresholdUsd > 0) {
          db.prepare(`INSERT OR REPLACE INTO queue_state (key, value) VALUES ('config.job_cost_threshold_usd', ?)`).run(String(jobCostThresholdUsd))
        }
      }
      res.json({ ok: true })
    } catch (err) {
      console.error('[project-router] budget patch error:', err)
      res.status(500).json({ error: 'Failed to update budget' })
    }
  })

  router.get('/:projectId/issues', (req: Request, res: Response) => {
    const { project, db } = ctx(req)
    try {
      const config = getConfig(project.path, db, project.name)
      const tracker = config.issueTracker.active
      if (!tracker) {
        res.status(503).json({ error: 'No issue tracker configured', trackers: config.issueTracker })
        return
      }
      const search = req.query.search as string | undefined
      const label = req.query.label as string | undefined
      const issues = fetchIssues(tracker, { search, label, repo: config.project.repo, cwd: project.path })
      res.json(issues)
    } catch (err) {
      console.error('[project-router] issues error:', err)
      res.status(500).json({ error: 'Failed to fetch issues' })
    }
  })

  // ─── Chat routes ─────────────────────────────────────────────────────────────

  router.get('/:projectId/chat/conversations', (req: Request, res: Response) => {
    const conversations = listConversations(ctx(req).db)
    res.json({ conversations })
  })

  router.post('/:projectId/chat/conversations', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const model = (req.body?.model as string | undefined) ?? 'claude-sonnet-4-5'
    const id = uuidv4()
    createConversation(db, { id, model })
    const conversation = getConversation(db, id) as ChatConversationRow
    res.status(201).json({ conversation })
  })

  router.get('/:projectId/chat/conversations/:id', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const conversation = getConversation(db, req.params.id as string)
    if (!conversation) { res.status(404).json({ error: 'Conversation not found' }); return }
    const messages = getMessages(db, req.params.id as string)
    res.json({ conversation, messages })
  })

  router.delete('/:projectId/chat/conversations/:id', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const conversation = getConversation(db, req.params.id as string)
    if (!conversation) { res.status(404).json({ error: 'Conversation not found' }); return }
    deleteConversation(db, req.params.id as string)
    res.json({ ok: true })
  })

  router.patch('/:projectId/chat/conversations/:id', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const conversation = getConversation(db, req.params.id as string)
    if (!conversation) { res.status(404).json({ error: 'Conversation not found' }); return }
    const { title, model } = req.body ?? {}
    const patch: { title?: string; model?: string } = {}
    if (title !== undefined) patch.title = title
    if (model !== undefined) patch.model = model
    updateConversation(db, req.params.id as string, patch)
    const updated = getConversation(db, req.params.id as string) as ChatConversationRow
    res.json({ ok: true, conversation: updated })
  })

  router.get('/:projectId/chat/conversations/:id/messages', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const conversation = getConversation(db, req.params.id as string)
    if (!conversation) { res.status(404).json({ error: 'Conversation not found' }); return }
    const messages = getMessages(db, req.params.id as string)
    res.json({ messages })
  })

  router.post('/:projectId/chat/conversations/:id/messages', async (req: Request, res: Response) => {
    const { db, chatManager } = ctx(req)
    const conversation = getConversation(db, req.params.id as string)
    if (!conversation) { res.status(404).json({ error: 'Conversation not found' }); return }
    const text = req.body?.text as string | undefined
    if (!text || !text.trim()) { res.status(400).json({ error: 'text is required' }); return }
    if (chatManager.isActive(req.params.id as string)) {
      res.status(409).json({ error: 'CONVERSATION_BUSY' }); return
    }
    const lightweight = req.body?.lightweight === true
    const maxTurns = typeof req.body?.maxTurns === 'number' ? req.body.maxTurns : undefined
    res.status(202).json({ ok: true })
    chatManager.sendMessage(req.params.id as string, text.trim(), { lightweight, maxTurns }).catch((err) => {
      console.error('[project-router] chat sendMessage error:', err)
    })
  })

  router.delete('/:projectId/chat/conversations/:id/messages/stream', (req: Request, res: Response) => {
    const { chatManager } = ctx(req)
    if (!chatManager.isActive(req.params.id as string)) {
      res.status(404).json({ error: 'No active stream for this conversation' }); return
    }
    chatManager.abort(req.params.id as string)
    res.json({ ok: true })
  })

  // ─── Install-config route ─────────────────────────────────────────────────────

  router.post('/:projectId/setup/install-config', (req: Request, res: Response) => {
    const { project } = ctx(req)
    const config = req.body ?? {}
    if (typeof config !== 'object' || Array.isArray(config)) {
      res.status(400).json({ error: 'Request body must be a config object' }); return
    }
    const configDir = path.join(project.path, '.specrails')
    const configPath = path.join(configDir, 'install-config.yaml')
    try {
      fs.mkdirSync(configDir, { recursive: true })
      const yaml = serializeInstallConfigYaml(config as Record<string, unknown>)
      fs.writeFileSync(configPath, yaml, 'utf-8')
      res.json({ ok: true, path: configPath })
    } catch (err) {
      res.status(500).json({ error: `Failed to write install-config.yaml: ${err}` })
    }
  })

  // ─── Enrich routes (v3) + Setup aliases (v1/v2 backward compat) ──────────────

  router.post('/:projectId/setup/install', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    if (setupManager.isInstalling(project.id)) {
      res.status(409).json({ error: 'Install already in progress' }); return
    }
    res.status(202).json({ ok: true })
    setupManager.startInstall(project.id, project.path)
  })

  router.post('/:projectId/setup/quick-install', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    if (setupManager.isInstalling(project.id)) {
      res.status(409).json({ error: 'Install already in progress' }); return
    }
    const installConfig = req.body ?? {}
    res.status(202).json({ ok: true })
    setupManager.startQuickInstall(project.id, project.path, installConfig)
  })

  router.post('/:projectId/enrich/start', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    if (setupManager.isEnriching(project.id)) {
      res.status(409).json({ error: 'Enrich already in progress' }); return
    }
    res.status(202).json({ ok: true })
    setupManager.startEnrich(project.id, project.path, project.provider)
  })

  // Legacy alias: /setup/start → /enrich/start
  router.post('/:projectId/setup/start', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    if (setupManager.isEnriching(project.id)) {
      res.status(409).json({ error: 'Setup already in progress' }); return
    }
    res.status(202).json({ ok: true })
    setupManager.startEnrich(project.id, project.path, project.provider)
  })

  router.post('/:projectId/enrich/message', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    const { sessionId, message } = req.body ?? {}
    if (!sessionId || typeof sessionId !== 'string') {
      res.status(400).json({ error: 'sessionId is required' }); return
    }
    if (!message || typeof message !== 'string' || !message.trim()) {
      res.status(400).json({ error: 'message is required' }); return
    }
    if (setupManager.isEnriching(project.id)) {
      res.status(409).json({ error: 'Enrich already in progress' }); return
    }
    res.status(202).json({ ok: true })
    setupManager.resumeEnrich(project.id, project.path, sessionId, message.trim(), project.provider)
  })

  // Legacy alias: /setup/message → /enrich/message
  router.post('/:projectId/setup/message', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    const { sessionId, message } = req.body ?? {}
    if (!sessionId || typeof sessionId !== 'string') {
      res.status(400).json({ error: 'sessionId is required' }); return
    }
    if (!message || typeof message !== 'string' || !message.trim()) {
      res.status(400).json({ error: 'message is required' }); return
    }
    if (setupManager.isEnriching(project.id)) {
      res.status(409).json({ error: 'Setup already in progress' }); return
    }
    res.status(202).json({ ok: true })
    setupManager.resumeEnrich(project.id, project.path, sessionId, message.trim(), project.provider)
  })

  router.get('/:projectId/setup/checkpoints', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    const checkpoints = setupManager.getCheckpointStatus(project.id, project.path)
    const savedSessionId = getProjectSetupSession(registry.hubDb, project.id)
    res.json({
      checkpoints,
      isInstalling: setupManager.isInstalling(project.id),
      isSettingUp: setupManager.isEnriching(project.id),
      isEnriching: setupManager.isEnriching(project.id),
      tier: setupManager.getInstallTier(project.id) ?? null,
      savedSessionId: savedSessionId ?? null,
      logLines: setupManager.getInstallLog(project.id),
      summary: setupManager.getSummary(project.path),
    })
  })

  router.post('/:projectId/setup/abort', (req: Request, res: Response) => {
    const { project, setupManager } = ctx(req)
    setupManager.abort(project.id)
    res.json({ ok: true })
  })

  // ─── Proposal routes ──────────────────────────────────────────────────────

  router.get('/:projectId/propose', (req: Request, res: Response) => {
    const limit = Math.min(parseInt(String(req.query.limit ?? '20'), 10) || 20, 100)
    const offset = parseInt(String(req.query.offset ?? '0'), 10) || 0
    const result = listProposals(ctx(req).db, { limit, offset })
    res.json(result)
  })

  router.post('/:projectId/propose', async (req: Request, res: Response) => {
    const { idea } = req.body ?? {}
    if (!idea || typeof idea !== 'string' || !idea.trim()) {
      res.status(400).json({ error: 'idea is required' }); return
    }
    // Pre-check: does the propose-feature command exist in this project?
    const testCmd = `/sr:propose-feature test`
    const resolved = resolveCommand(testCmd, ctx(req).project.path)
    if (resolved === testCmd) {
      res.status(400).json({ error: 'This project does not have the /sr:propose-feature command installed. Run "npx specrails-core@latest" to update.' }); return
    }
    const id = uuidv4()
    createProposal(ctx(req).db, { id, idea: idea.trim() })
    res.status(202).json({ proposalId: id })
    ctx(req).proposalManager.startExploration(id, idea.trim()).catch((err) => {
      console.error('[project-router] proposal startExploration error:', err)
    })
  })

  router.get('/:projectId/propose/:id', (req: Request, res: Response) => {
    const proposal = getProposal(ctx(req).db, req.params.id as string)
    if (!proposal) { res.status(404).json({ error: 'Proposal not found' }); return }
    res.json({ proposal })
  })

  router.post('/:projectId/propose/:id/refine', async (req: Request, res: Response) => {
    const proposal = getProposal(ctx(req).db, req.params.id as string)
    if (!proposal) { res.status(404).json({ error: 'Proposal not found' }); return }
    const { feedback } = req.body ?? {}
    if (!feedback || typeof feedback !== 'string' || !feedback.trim()) {
      res.status(400).json({ error: 'feedback is required' }); return
    }
    if (ctx(req).proposalManager.isActive(req.params.id as string)) {
      res.status(409).json({ error: 'PROPOSAL_BUSY' }); return
    }
    if (proposal.status !== 'review') {
      res.status(409).json({ error: 'Proposal is not in review state' }); return
    }
    res.status(202).json({ ok: true })
    ctx(req).proposalManager.sendRefinement(req.params.id as string, feedback.trim()).catch((err) => {
      console.error('[project-router] proposal sendRefinement error:', err)
    })
  })

  router.post('/:projectId/propose/:id/create-issue', async (req: Request, res: Response) => {
    const proposal = getProposal(ctx(req).db, req.params.id as string)
    if (!proposal) { res.status(404).json({ error: 'Proposal not found' }); return }
    if (ctx(req).proposalManager.isActive(req.params.id as string)) {
      res.status(409).json({ error: 'PROPOSAL_BUSY' }); return
    }
    if (proposal.status !== 'review') {
      res.status(409).json({ error: 'Proposal is not in review state' }); return
    }
    res.status(202).json({ ok: true })
    ctx(req).proposalManager.createIssue(req.params.id as string).catch((err) => {
      console.error('[project-router] proposal createIssue error:', err)
    })
  })

  router.delete('/:projectId/propose/:id', (req: Request, res: Response) => {
    const proposal = getProposal(ctx(req).db, req.params.id as string)
    if (!proposal) { res.status(404).json({ error: 'Proposal not found' }); return }
    ctx(req).proposalManager.cancel(req.params.id as string)
    res.json({ ok: true })
  })

  // ─── Feature Funnel ─────────────────────────────────────────────────────────

  router.get('/:projectId/changes', (req: Request, res: Response) => {
    const { project, queueManager } = ctx(req)
    const activeCommands = queueManager.getJobs()
      .filter((j) => j.status === 'running' || j.status === 'queued')
      .map((j) => j.command)
    const changes = readChanges(project.path, activeCommands)
    res.json({ changes })
  })

  // ─── Change Artifact Browser ─────────────────────────────────────────────────

  const ALLOWED_ARTIFACTS = new Set(['proposal.md', 'design.md', 'tasks.md', 'delta-spec.md', 'context-bundle.md'])

  router.get('/:projectId/changes/:changeId/artifacts/:artifact', (req: Request, res: Response) => {
    const changeId = req.params.changeId as string
    const artifact = req.params.artifact as string
    if (!ALLOWED_ARTIFACTS.has(artifact)) {
      res.status(400).json({ error: 'Invalid artifact name' }); return
    }
    // Sanitize changeId to prevent path traversal
    if (!/^[\w-]+$/.test(changeId)) {
      res.status(400).json({ error: 'Invalid change ID' }); return
    }
    const { project } = ctx(req)
    const changesRoot = path.join(project.path, 'openspec', 'changes')
    // Check active dir first, then archive
    let filePath = path.join(changesRoot, changeId, artifact)
    if (!fs.existsSync(filePath)) {
      filePath = path.join(changesRoot, 'archive', changeId, artifact)
    }
    if (!fs.existsSync(filePath)) {
      res.status(404).json({ error: 'Artifact not found' }); return
    }
    try {
      const content = fs.readFileSync(filePath, 'utf-8')
      res.json({ content, artifact, changeId })
    } catch {
      res.status(500).json({ error: 'Failed to read artifact' })
    }
  })

  // ─── Spec Launcher ───────────────────────────────────────────────────────────

  router.post('/:projectId/spec-launcher/start', (req: Request, res: Response) => {
    const { description } = req.body ?? {}
    if (!description || typeof description !== 'string' || !description.trim()) {
      res.status(400).json({ error: 'description is required' }); return
    }
    const launchId = uuidv4()
    res.status(202).json({ launchId })
    ctx(req).specLauncherManager.launch(launchId, description.trim()).catch((err) => {
      console.error('[project-router] spec-launcher error:', err)
    })
  })

  router.delete('/:projectId/spec-launcher/:launchId', (req: Request, res: Response) => {
    const { specLauncherManager } = ctx(req)
    if (!specLauncherManager.isActive(req.params.launchId as string)) {
      res.status(404).json({ error: 'No active launch with that ID' }); return
    }
    specLauncherManager.cancel(req.params.launchId as string)
    res.json({ ok: true })
  })

  // ─── Job Templates ────────────────────────────────────────────────────────

  function templateToPublic(row: ReturnType<typeof getTemplate>): JobTemplate | null {
    if (!row) return null
    return {
      id: row.id,
      name: row.name,
      description: row.description,
      commands: JSON.parse(row.commands) as string[],
      created_at: row.created_at,
      updated_at: row.updated_at,
    }
  }

  router.get('/:projectId/templates', (req: Request, res: Response) => {
    const rows = listTemplates(ctx(req).db)
    const templates = rows.map((r) => templateToPublic(r)!)
    res.json({ templates })
  })

  router.post('/:projectId/templates', (req: Request, res: Response) => {
    const { name, description, commands } = req.body ?? {}
    if (!name || typeof name !== 'string' || !name.trim()) {
      res.status(400).json({ error: 'name is required' }); return
    }
    if (!Array.isArray(commands) || commands.length === 0) {
      res.status(400).json({ error: 'commands must be a non-empty array' }); return
    }
    if (commands.some((c: unknown) => typeof c !== 'string' || !String(c).trim())) {
      res.status(400).json({ error: 'each command must be a non-empty string' }); return
    }
    const id = uuidv4()
    try {
      createTemplate(ctx(req).db, {
        id,
        name: name.trim(),
        description: description && typeof description === 'string' ? description.trim() : undefined,
        commands: commands.map((c: string) => c.trim()),
      })
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : ''
      if (msg.includes('UNIQUE constraint failed')) {
        res.status(409).json({ error: 'A template with that name already exists' }); return
      }
      console.error('[project-router] create template error:', err)
      res.status(500).json({ error: 'Internal server error' }); return
    }
    const created = templateToPublic(getTemplate(ctx(req).db, id))!
    res.status(201).json({ template: created })
  })

  router.get('/:projectId/templates/:templateId', (req: Request, res: Response) => {
    const row = getTemplate(ctx(req).db, req.params.templateId as string)
    if (!row) { res.status(404).json({ error: 'Template not found' }); return }
    res.json({ template: templateToPublic(row)! })
  })

  router.patch('/:projectId/templates/:templateId', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const templateId = req.params.templateId as string
    const row = getTemplate(db, templateId)
    if (!row) { res.status(404).json({ error: 'Template not found' }); return }
    const { name, description, commands } = req.body ?? {}
    const patch: { name?: string; description?: string | null; commands?: string[] } = {}
    if (name !== undefined) {
      if (typeof name !== 'string' || !name.trim()) {
        res.status(400).json({ error: 'name must be a non-empty string' }); return
      }
      patch.name = name.trim()
    }
    if (description !== undefined) {
      patch.description = description === null ? null : String(description).trim() || null
    }
    if (commands !== undefined) {
      if (!Array.isArray(commands) || commands.length === 0) {
        res.status(400).json({ error: 'commands must be a non-empty array' }); return
      }
      if (commands.some((c: unknown) => typeof c !== 'string' || !String(c).trim())) {
        res.status(400).json({ error: 'each command must be a non-empty string' }); return
      }
      patch.commands = commands.map((c: string) => c.trim())
    }
    try {
      updateTemplate(db, templateId, patch)
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : ''
      if (msg.includes('UNIQUE constraint failed')) {
        res.status(409).json({ error: 'A template with that name already exists' }); return
      }
      console.error('[project-router] update template error:', err)
      res.status(500).json({ error: 'Internal server error' }); return
    }
    const updated = templateToPublic(getTemplate(db, templateId))!
    res.json({ ok: true, template: updated })
  })

  router.delete('/:projectId/templates/:templateId', (req: Request, res: Response) => {
    const { db } = ctx(req)
    const row = getTemplate(db, req.params.templateId as string)
    if (!row) { res.status(404).json({ error: 'Template not found' }); return }
    deleteTemplate(db, req.params.templateId as string)
    res.json({ ok: true })
  })

  router.post('/:projectId/templates/:templateId/run', (req: Request, res: Response) => {
    const { db, queueManager } = ctx(req)
    const row = getTemplate(db, req.params.templateId as string)
    if (!row) { res.status(404).json({ error: 'Template not found' }); return }
    const commands = JSON.parse(row.commands) as string[]
    const chain = req.body?.chain !== false // default: chain jobs as pipeline
    const jobIds: string[] = []
    try {
      const pipelineId = chain && commands.length > 1 ? uuidv4() : undefined
      let prevJobId: string | null = null
      for (const command of commands) {
        const job = queueManager.enqueue(command, 'normal', {
          dependsOnJobId: chain ? (prevJobId ?? undefined) : undefined,
          pipelineId,
        })
        jobIds.push(job.id)
        prevJobId = job.id
      }
    } catch (err) {
      if (err instanceof ClaudeNotFoundError) {
        res.status(400).json({ error: err.message }); return
      }
      console.error('[project-router] template run error:', err)
      res.status(500).json({ error: 'Internal server error' }); return
    }
    res.status(202).json({ ok: true, jobIds, templateId: row.id, templateName: row.name })
  })

  // ─── Integration contract ──────────────────────────────────────────────────

  const DEFAULT_TICKET_CAPABILITIES = ['crud', 'labels', 'status', 'priorities', 'dependencies']
  const DEFAULT_TICKET_STORAGE_PATH = '.specrails/local-tickets.json'

  // GET /:projectId/integration-contract — Return the project's integration contract with ticketProvider
  router.get('/:projectId/integration-contract', (req: Request, res: Response) => {
    const projectPath = ctx(req).project.path
    const contractFile = path.join(projectPath, '.claude', 'integration-contract.json')
    let rawContract: Record<string, unknown> = {}
    let source: 'contract' | 'default' = 'default'

    if (fs.existsSync(contractFile)) {
      try {
        rawContract = JSON.parse(fs.readFileSync(contractFile, 'utf-8'))
        source = 'contract'
      } catch {
        // malformed contract — fall back to defaults
      }
    }

    const rawProvider = rawContract.ticketProvider as { type?: string; storagePath?: string; capabilities?: string[] } | undefined
    const storagePath = rawProvider?.storagePath ?? DEFAULT_TICKET_STORAGE_PATH
    const ticketProvider = {
      type: rawProvider?.type ?? 'local',
      storagePath: path.resolve(projectPath, storagePath),
      capabilities: rawProvider?.capabilities ?? DEFAULT_TICKET_CAPABILITIES,
    }

    res.json({ ticketProvider, source })
  })

  // ─── Tickets ──────────────────────────────────────────────────────────────────

  /** Resolve the ticket storage file path for a project */
  function ticketPath(req: Request): string {
    return resolveTicketStoragePath(ctx(req).project.path)
  }

  // GET /:projectId/tickets — List all tickets with optional filters
  router.get('/:projectId/tickets', (req: Request, res: Response) => {
    try {
      const filePath = ticketPath(req)
      const store = readStore(filePath)
      const allTickets = Object.values(store.tickets)
      const filtered = filterTickets(allTickets, {
        status: req.query.status as string | undefined,
        label: req.query.label as string | undefined,
        q: req.query.q as string | undefined,
      })
      // Sort by updated_at descending
      filtered.sort((a, b) => (b.updated_at || '').localeCompare(a.updated_at || ''))
      res.json({ tickets: filtered, revision: store.revision, total: allTickets.length })
    } catch (err) {
      console.error('[project-router] ticket list error:', err)
      res.status(500).json({ error: 'Failed to read tickets' })
    }
  })

  // GET /:projectId/tickets/:id — Get single ticket
  router.get('/:projectId/tickets/:id', (req: Request, res: Response) => {
    const ticketId = req.params.id as string
    if (!/^\d+$/.test(ticketId)) {
      res.status(400).json({ error: 'Invalid ticket ID' }); return
    }
    try {
      const store = readStore(ticketPath(req))
      const ticket = store.tickets[ticketId]
      if (!ticket) {
        res.status(404).json({ error: 'Ticket not found' }); return
      }
      res.json({ ticket, revision: store.revision })
    } catch (err) {
      console.error('[project-router] ticket get error:', err)
      res.status(500).json({ error: 'Failed to read ticket' })
    }
  })

  // POST /:projectId/tickets/generate-spec — Fast AI spec generation (no codebase exploration)
  router.post('/:projectId/tickets/generate-spec', async (req: Request, res: Response) => {
    const idea = req.body?.idea as string | undefined
    if (!idea?.trim()) {
      res.status(400).json({ error: 'idea is required' }); return
    }
    const attachmentIds = Array.isArray(req.body?.attachmentIds)
      ? (req.body.attachmentIds as unknown[]).filter((x): x is string => typeof x === 'string')
      : []
    const pendingSpecId = typeof req.body?.pendingSpecId === 'string' ? (req.body.pendingSpecId as string) : null
    if (attachmentIds.length > 0 && !pendingSpecId) {
      res.status(400).json({ error: 'pendingSpecId is required when attachmentIds are provided' }); return
    }

    const { project, broadcast, ticketWatcher } = ctx(req)
    const provider = project.provider ?? 'claude'
    const requestId = uuidv4()
    const projectId = project.id
    const filePath = ticketPath(req)

    let hasAttachments = false
    let baseUserPrompt = `Generate a spec for the following idea:\n\n${idea.trim()}`
    let imageFlags: string[] = []
    if (attachmentIds.length > 0 && pendingSpecId) {
      try {
        const extracted = await attachmentManager.getClaudeArgs(project.slug, pendingSpecId, attachmentIds)
        imageFlags = extracted.imageFlags
        if (extracted.textBlocks.length > 0) {
          hasAttachments = true
          baseUserPrompt = `${baseUserPrompt}\n\n## Attached Resources\n\n${extracted.textBlocks.join('\n\n')}`
        }
      } catch (err) {
        console.error('[project-router] generate-spec attachment extraction error:', err)
      }
    }

    const codebaseRule = hasAttachments
      ? `- Do NOT explore the project codebase. The resources inside <user-attachment> blocks below are pre-loaded context the user intentionally provided — read and use them freely.`
      : `- Do NOT read any files or explore the codebase. Work purely from the user's description.`

    let baseSystemPrompt =
      `You are a senior product engineer generating a structured spec proposal.\n\n` +
      `RULES:\n` +
      `${codebaseRule}\n` +
      `- Do NOT create files, tickets, or issues.\n` +
      `- Output ONLY the structured markdown below. No preamble, no explanation.\n\n` +
      `REQUIRED FORMAT:\n` +
      `## Spec Title\n[Concise, action-oriented title]\n\n` +
      `## Problem Statement\n[2-3 sentences]\n\n` +
      `## Proposed Solution\n[3-5 sentences]\n\n` +
      `## Out of Scope\n[Bullet list]\n\n` +
      `## Acceptance Criteria\n[Numbered list of testable outcomes]\n\n` +
      `## Technical Considerations\n[Bullet list]\n\n` +
      `## Estimated Complexity\n[Low/Medium/High/Very High + one sentence justification]`

    if (hasAttachments) baseSystemPrompt = `${baseSystemPrompt}\n\n${USER_ATTACHMENT_SYSTEM_NOTE}`

    const systemPrompt = baseSystemPrompt
    const userPrompt = baseUserPrompt

    let binary: string
    let args: string[]

    if (provider === 'codex') {
      binary = 'codex'
      // Use gpt-5.4-mini (balanced preset default for Codex per CODEX_MODELS/PRESET_DEFAULTS in ModelSelector); never hardcode o4-mini
      args = ['exec', `${systemPrompt}\n\n${userPrompt}`, '--model', 'gpt-5.4-mini']
    } else {
      binary = 'claude'
      args = [
        '--dangerously-skip-permissions',
        '--tools', 'default',
        '--output-format', 'stream-json',
        '--verbose',
        '--max-turns', hasAttachments ? '3' : '1',
        ...imageFlags,
        '--system-prompt', systemPrompt,
        '-p', userPrompt,
      ]
    }

    const child = spawn(binary, args, {
      env: process.env,
      shell: false,
      stdio: ['ignore', 'pipe', 'pipe'],
      cwd: project.path,
    })

    res.status(202).json({ requestId })

    let buffer = ''
    const stdoutReader = createInterface({ input: child.stdout!, crlfDelay: Infinity })

    stdoutReader.on('line', (line) => {
      if (provider === 'codex') {
        if (line) {
          buffer += line + '\n'
          const msg: SpecGenStreamMessage = {
            type: 'spec_gen_stream', projectId, requestId,
            delta: line + '\n', timestamp: new Date().toISOString(),
          }
          broadcast(msg)
        }
      } else {
        let parsed: Record<string, unknown> | null = null
        try { parsed = JSON.parse(line) } catch { /* skip */ }
        if (!parsed) return

        if ((parsed.type as string) === 'assistant') {
          const msg = parsed.message as { content?: Array<{ type: string; text?: string }> } | undefined
          const texts = (msg?.content ?? [])
            .filter((c) => c.type === 'text')
            .map((c) => c.text ?? '')
          const newText = texts.join('')
          if (newText) {
            buffer += newText
            const wsMsg: SpecGenStreamMessage = {
              type: 'spec_gen_stream', projectId, requestId,
              delta: newText, timestamp: new Date().toISOString(),
            }
            broadcast(wsMsg)
          }
        }
      }
    })

    child.on('close', async (code) => {
      if (code === 0 && buffer.trim()) {
        // Extract title from generated spec
        const titleMatch = buffer.match(/##\s*Spec Title\s*\n+(.+)/)
        const specTitle = titleMatch ? titleMatch[1].trim() : idea.trim().slice(0, 80)

        // Extract complexity for priority mapping
        const complexityMatch = buffer.match(/##\s*Estimated Complexity\s*\n+(\w+)/)
        const complexity = complexityMatch ? complexityMatch[1].toLowerCase() : 'medium'
        const priority = complexity === 'low' ? 'low' : complexity === 'high' || complexity === 'very' ? 'high' : 'medium'

        // Create ticket directly
        try {
          const now = new Date().toISOString()
          let created: import('./ticket-store').Ticket | undefined
          const store = mutateStore(filePath, (s) => {
            const id = s.next_id++
            const ticket: import('./ticket-store').Ticket = {
              id,
              title: specTitle,
              description: buffer.trim(),
              status: 'todo',
              priority: priority as 'low' | 'medium' | 'high',
              labels: ['spec-proposal'],
              assignee: null,
              prerequisites: [],
              metadata: {},
              comments: [],
              created_at: now,
              updated_at: now,
              created_by: 'sr-product-engineer',
              source: 'propose-spec',
            }
            s.tickets[String(id)] = ticket
            created = ticket
          })
          ticketWatcher.notifyHubWrite(store.revision)

          // Migrate attachments from pendingSpecId → real ticket id (if any were uploaded).
          // Must complete BEFORE broadcasting ticket_created so WS listeners see the populated attachments[].
          if (pendingSpecId && created) {
            try {
              const migrated = await attachmentManager.renameTicketDir({
                slug: project.slug,
                pendingId: pendingSpecId,
                realTicketId: created.id,
                projectPath: project.path,
              })
              if (migrated.length > 0) {
                created.attachments = migrated
              }
            } catch (err) {
              console.error('[project-router] generate-spec attachment migration error:', err)
            }
          }

          const ticketMsg: TicketCreatedMessage = {
            type: 'ticket_created', ticket: created! as unknown as LocalTicket,
            projectId, timestamp: new Date().toISOString(),
          }
          broadcast(ticketMsg)

          const doneMsg: SpecGenDoneMessage = {
            type: 'spec_gen_done', projectId, requestId,
            ticket: created! as unknown as LocalTicket, timestamp: new Date().toISOString(),
          }
          broadcast(doneMsg)
        } catch (err) {
          console.error('[project-router] generate-spec ticket creation error:', err)
          const errMsg: SpecGenErrorMessage = {
            type: 'spec_gen_error', projectId, requestId,
            error: 'Failed to create ticket', timestamp: new Date().toISOString(),
          }
          broadcast(errMsg)
        }
      } else {
        const msg: SpecGenErrorMessage = {
          type: 'spec_gen_error', projectId, requestId,
          error: code === 0 ? 'Empty response from AI' : `Process exited with code ${code}`,
          timestamp: new Date().toISOString(),
        }
        broadcast(msg)
      }
    })
  })

  // POST /:projectId/tickets — Create new ticket
  router.post('/:projectId/tickets', (req: Request, res: Response) => {
    const { title, description, status, priority, labels, assignee, prerequisites, metadata, source } = req.body ?? {}
    if (!title || typeof title !== 'string' || !title.trim()) {
      res.status(400).json({ error: 'title is required' }); return
    }
    if (status !== undefined && !isValidStatus(status)) {
      res.status(400).json({ error: 'status must be one of: todo, in_progress, done, cancelled' }); return
    }
    if (priority !== undefined && !isValidPriority(priority)) {
      res.status(400).json({ error: 'priority must be one of: critical, high, medium, low' }); return
    }
    try {
      const filePath = ticketPath(req)
      const now = new Date().toISOString()
      let created: Ticket | undefined
      const store = mutateStore(filePath, (s) => {
        const id = s.next_id++
        const ticket: Ticket = {
          id,
          title: title.trim(),
          description: typeof description === 'string' ? description : '',
          status: status ?? 'todo',
          priority: priority ?? 'medium',
          labels: Array.isArray(labels) ? labels.filter((l: unknown) => typeof l === 'string') : [],
          assignee: typeof assignee === 'string' ? assignee : null,
          prerequisites: Array.isArray(prerequisites) ? prerequisites.filter((p: unknown) => typeof p === 'number') : [],
          metadata: typeof metadata === 'object' && metadata !== null ? metadata : {},
          comments: [],
          created_at: now,
          updated_at: now,
          created_by: 'hub',
          source: source === 'product-backlog' || source === 'propose-spec' || source === 'manual' ? source : 'hub',
        }
        s.tickets[String(id)] = ticket
        created = ticket
      })
      const { broadcast, ticketWatcher } = ctx(req)
      ticketWatcher.notifyHubWrite(store.revision)
      const msg: TicketCreatedMessage = { type: 'ticket_created', ticket: created! as unknown as LocalTicket, projectId: ctx(req).project.id, timestamp: new Date().toISOString() }
      broadcast(msg)
      res.status(201).json({ ticket: created!, revision: store.revision })
    } catch (err) {
      console.error('[project-router] ticket create error:', err)
      res.status(500).json({ error: 'Failed to create ticket' })
    }
  })

  // PATCH /:projectId/tickets/:id — Update ticket fields
  router.patch('/:projectId/tickets/:id', (req: Request, res: Response) => {
    const ticketId = req.params.id as string
    if (!/^\d+$/.test(ticketId)) {
      res.status(400).json({ error: 'Invalid ticket ID' }); return
    }
    const { title, description, status, priority, labels, assignee, prerequisites, metadata } = req.body ?? {}
    if (status !== undefined && !isValidStatus(status)) {
      res.status(400).json({ error: 'status must be one of: todo, in_progress, done, cancelled' }); return
    }
    if (priority !== undefined && !isValidPriority(priority)) {
      res.status(400).json({ error: 'priority must be one of: critical, high, medium, low' }); return
    }
    if (title !== undefined && (typeof title !== 'string' || !title.trim())) {
      res.status(400).json({ error: 'title cannot be empty' }); return
    }
    try {
      const filePath = ticketPath(req)
      let updated: Ticket | undefined
      const store = mutateStore(filePath, (s) => {
        const ticket = s.tickets[ticketId]
        if (!ticket) return
        if (title !== undefined) ticket.title = title.trim()
        if (description !== undefined) ticket.description = description
        if (status !== undefined) ticket.status = status
        if (priority !== undefined) ticket.priority = priority
        if (labels !== undefined && Array.isArray(labels)) ticket.labels = labels.filter((l: unknown) => typeof l === 'string')
        if (assignee !== undefined) ticket.assignee = typeof assignee === 'string' ? assignee : null
        if (prerequisites !== undefined && Array.isArray(prerequisites)) ticket.prerequisites = prerequisites.filter((p: unknown) => typeof p === 'number')
        if (metadata !== undefined && typeof metadata === 'object' && metadata !== null) {
          ticket.metadata = { ...ticket.metadata, ...metadata }
        }
        ticket.updated_at = new Date().toISOString()
        updated = ticket
      })
      if (!updated) {
        res.status(404).json({ error: 'Ticket not found' }); return
      }
      const { broadcast, ticketWatcher } = ctx(req)
      ticketWatcher.notifyHubWrite(store.revision)
      const msg: TicketUpdatedMessage = { type: 'ticket_updated', ticket: updated as unknown as LocalTicket, projectId: ctx(req).project.id, timestamp: new Date().toISOString() }
      broadcast(msg)
      res.json({ ticket: updated, revision: store.revision })
    } catch (err) {
      console.error('[project-router] ticket update error:', err)
      res.status(500).json({ error: 'Failed to update ticket' })
    }
  })

  // POST /:projectId/tickets/:id/ai-edit — AI-powered description editing
  const _aiEditProcesses = new Map<string, import('child_process').ChildProcess>()

  router.post('/:projectId/tickets/:id/ai-edit', async (req: Request, res: Response) => {
    const ticketId = req.params.id as string
    if (!/^\d+$/.test(ticketId)) {
      res.status(400).json({ error: 'Invalid ticket ID' }); return
    }
    const instructions = req.body?.instructions as string | undefined
    const currentDescription = req.body?.description as string | undefined
    if (!instructions?.trim()) {
      res.status(400).json({ error: 'instructions is required' }); return
    }
    if (!currentDescription) {
      res.status(400).json({ error: 'description is required' }); return
    }
    const attachmentIds = Array.isArray(req.body?.attachmentIds)
      ? (req.body.attachmentIds as unknown[]).filter((x): x is string => typeof x === 'string')
      : []
    const priorInstructions = Array.isArray(req.body?.priorInstructions)
      ? (req.body.priorInstructions as unknown[]).filter((x): x is string => typeof x === 'string')
      : []
    const priorProposalRaw = req.body?.priorProposal
    const priorProposal = typeof priorProposalRaw === 'string' && priorProposalRaw.length > 0 ? priorProposalRaw : null
    const isRefinement = priorProposal !== null

    const { project, broadcast } = ctx(req)
    const provider = project.provider ?? 'claude'
    const requestId = uuidv4()
    const projectId = project.id

    // Build the focused pre-prompt
    const baseRules =
      `- Output ONLY the modified description in markdown. No preamble, no explanation, no wrapping.\n` +
      `- Preserve the existing markdown structure and section headings.\n` +
      `- If the user asks to add technical details, briefly check CLAUDE.md and the project directory structure (ls, not deep reads) to ground your edits.\n` +
      `- Keep it concise and actionable.\n` +
      `- Do NOT create files, tickets, or issues. Only output text.`

    const refinementRule = isRefinement
      ? `\n- You are editing an in-progress draft, not the saved description. Apply the new refinement to the Latest Draft below.`
      : ''

    let systemPrompt =
      `You are a spec editor. You will receive a ticket description and user instructions for how to modify it. ` +
      `Your job is to produce an improved version of the description.\n\n` +
      `RULES:\n` +
      `${baseRules}${refinementRule}`

    let userPrompt = isRefinement
      ? `## Current Description (saved baseline — do not rewrite)\n\n${currentDescription}\n\n` +
        `## Prior Refinement Turns\n\n${priorInstructions.map((s, i) => `${i + 1}. ${s}`).join('\n')}\n\n` +
        `## Latest Draft (from previous turn — apply the new refinement to this)\n\n${priorProposal}\n\n` +
        `## New Refinement\n\n${instructions.trim()}\n\n` +
        `Output the updated description now.`
      : `## Current Description\n\n${currentDescription}\n\n` +
        `## User Instructions\n\n${instructions.trim()}\n\n` +
        `Output the modified description now.`

    let imageFlags: string[] = []
    if (attachmentIds.length > 0) {
      try {
        const extracted = await attachmentManager.getClaudeArgs(project.slug, ticketId, attachmentIds)
        imageFlags = extracted.imageFlags
        if (extracted.textBlocks.length > 0) {
          systemPrompt = `${systemPrompt}\n\n${USER_ATTACHMENT_SYSTEM_NOTE}`
          userPrompt = `${userPrompt}\n\n## Attached Files\n\n${extracted.textBlocks.join('\n\n')}`
        }
      } catch (err) {
        console.error('[project-router] ai-edit attachment extraction error:', err)
      }
    }

    let binary: string
    let args: string[]

    if (provider === 'codex') {
      binary = 'codex'
      // Use gpt-5.4-mini (balanced preset default for Codex per CODEX_MODELS/PRESET_DEFAULTS in ModelSelector); never hardcode o4-mini
      args = ['exec', `${systemPrompt}\n\n${userPrompt}`, '--model', 'gpt-5.4-mini']
    } else {
      binary = 'claude'
      args = [
        '--dangerously-skip-permissions',
        '--tools', 'default',
        '--output-format', 'stream-json',
        '--verbose',
        '--max-turns', '4',
        ...imageFlags,
        '--system-prompt', systemPrompt,
        '-p', userPrompt,
      ]
    }

    const child = spawn(binary, args, {
      env: process.env,
      shell: false,
      stdio: ['ignore', 'pipe', 'pipe'],
      cwd: project.path,
    })

    _aiEditProcesses.set(requestId, child)
    res.status(202).json({ requestId })

    let buffer = ''
    const stdoutReader = createInterface({ input: child.stdout!, crlfDelay: Infinity })

    stdoutReader.on('line', (line) => {
      if (provider === 'codex') {
        if (line) {
          buffer += line + '\n'
          const msg: TicketAiEditStreamMessage = {
            type: 'ticket_ai_edit_stream', projectId, ticketId: Number(ticketId),
            requestId, delta: line + '\n', timestamp: new Date().toISOString(),
          }
          broadcast(msg)
        }
      } else {
        let parsed: Record<string, unknown> | null = null
        try { parsed = JSON.parse(line) } catch { /* skip */ }
        if (!parsed) return

        if ((parsed.type as string) === 'assistant') {
          const msg = parsed.message as { content?: Array<{ type: string; text?: string }> } | undefined
          const texts = (msg?.content ?? [])
            .filter((c) => c.type === 'text')
            .map((c) => c.text ?? '')
          const newText = texts.join('')
          if (newText) {
            buffer += newText
            const wsMsg: TicketAiEditStreamMessage = {
              type: 'ticket_ai_edit_stream', projectId, ticketId: Number(ticketId),
              requestId, delta: newText, timestamp: new Date().toISOString(),
            }
            broadcast(wsMsg)
          }
        }
      }
    })

    child.on('close', (code) => {
      _aiEditProcesses.delete(requestId)
      if (code === 0 && buffer.trim()) {
        const msg: TicketAiEditDoneMessage = {
          type: 'ticket_ai_edit_done', projectId, ticketId: Number(ticketId),
          requestId, fullText: buffer.trim(), timestamp: new Date().toISOString(),
        }
        broadcast(msg)
      } else {
        const msg: TicketAiEditErrorMessage = {
          type: 'ticket_ai_edit_error', projectId, ticketId: Number(ticketId),
          requestId, error: code === 0 ? 'Empty response from AI' : `Process exited with code ${code}`,
          timestamp: new Date().toISOString(),
        }
        broadcast(msg)
      }
    })
  })

  router.delete('/:projectId/tickets/:id/ai-edit', (req: Request, res: Response) => {
    const requestId = req.query.requestId as string | undefined
    if (!requestId) { res.status(400).json({ error: 'requestId query param required' }); return }
    const child = _aiEditProcesses.get(requestId)
    if (!child?.pid) { res.status(404).json({ error: 'No active AI edit for this request' }); return }
    treeKill(child.pid, 'SIGTERM')
    _aiEditProcesses.delete(requestId)
    res.json({ ok: true })
  })

  // DELETE /:projectId/tickets/:id — Delete ticket
  router.delete('/:projectId/tickets/:id', (req: Request, res: Response) => {
    const ticketId = req.params.id as string
    if (!/^\d+$/.test(ticketId)) {
      res.status(400).json({ error: 'Invalid ticket ID' }); return
    }
    try {
      const filePath = ticketPath(req)
      let found = false
      const store = mutateStore(filePath, (s) => {
        if (s.tickets[ticketId]) {
          delete s.tickets[ticketId]
          found = true
        }
      })
      if (!found) {
        res.status(404).json({ error: 'Ticket not found' }); return
      }
      const { broadcast, ticketWatcher } = ctx(req)
      ticketWatcher.notifyHubWrite(store.revision)
      // Cascade-delete attachments for this ticket
      attachmentManager.deleteAll(ctx(req).project.slug, ticketId).catch((e) => {
        console.error('[project-router] attachment cascade delete failed:', e)
      })
      const msg: TicketDeletedMessage = { type: 'ticket_deleted', ticketId: Number(ticketId), projectId: ctx(req).project.id, timestamp: new Date().toISOString() }
      broadcast(msg)
      res.json({ ok: true, revision: store.revision })
    } catch (err) {
      console.error('[project-router] ticket delete error:', err)
      res.status(500).json({ error: 'Failed to delete ticket' })
    }
  })

  // ─── Ticket attachments ─────────────────────────────────────────────────────

  const attachmentUpload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 25 * 1024 * 1024 }, // 25 MB per file
    fileFilter: (_req, file, cb) => {
      if (SUPPORTED_MIME_TYPES.has(file.mimetype)) cb(null, true)
      else cb(null, false)
    },
  })

  /** A ticket key is either a numeric real id or a UUID (pendingSpecId). */
  function parseTicketKey(raw: string): { key: string; isPending: boolean } | null {
    if (/^\d+$/.test(raw)) return { key: raw, isPending: false }
    if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(raw)) {
      return { key: raw, isPending: true }
    }
    return null
  }

  router.post(
    '/:projectId/tickets/:ticketId/attachments',
    attachmentUpload.single('file'),
    async (req: Request, res: Response) => {
      const parsed = parseTicketKey(req.params.ticketId as string)
      if (!parsed) {
        res.status(400).json({ error: 'Invalid ticketId (must be numeric id or UUID)' })
        return
      }
      const file = (req as unknown as { file?: Express.Multer.File }).file
      if (!file) {
        res.status(400).json({ error: 'No file uploaded or file type unsupported' })
        return
      }
      if (!parsed.isPending) {
        const store = readStore(ticketPath(req))
        if (!store.tickets[parsed.key]) {
          res.status(404).json({ error: 'Ticket not found' })
          return
        }
      }
      try {
        const attachment = await attachmentManager.upload({
          slug: ctx(req).project.slug,
          ticketKey: parsed.key,
          projectPath: parsed.isPending ? null : ctx(req).project.path,
          file: {
            buffer: file.buffer,
            originalname: file.originalname,
            mimetype: file.mimetype,
            size: file.size,
          },
        })
        res.status(201).json({ attachment })
      } catch (err) {
        const status = (err as { status?: number }).status ?? 500
        const message = err instanceof Error ? err.message : 'Upload failed'
        console.error('[project-router] attachment upload error:', err)
        res.status(status).json({ error: message })
      }
    },
  )

  router.get('/:projectId/tickets/:ticketId/attachments', (req: Request, res: Response) => {
    const parsed = parseTicketKey(req.params.ticketId as string)
    if (!parsed) {
      res.status(400).json({ error: 'Invalid ticketId' })
      return
    }
    const attachments = attachmentManager.list(ctx(req).project.slug, parsed.key)
    res.json({ attachments })
  })

  router.get('/:projectId/tickets/:ticketId/attachments/:attachmentId', (req: Request, res: Response) => {
    const parsed = parseTicketKey(req.params.ticketId as string)
    if (!parsed) {
      res.status(400).json({ error: 'Invalid ticketId' })
      return
    }
    const attachmentId = req.params.attachmentId as string
    const slug = ctx(req).project.slug
    const meta = attachmentManager.getMeta(slug, parsed.key, attachmentId)
    const abs = meta ? attachmentManager.getFilePath(slug, parsed.key, attachmentId) : null
    if (!meta || !abs) {
      res.status(404).json({ error: 'Attachment not found' })
      return
    }
    res.setHeader('Content-Type', meta.mimeType)
    res.setHeader('Content-Disposition', `inline; filename="${meta.filename.replace(/"/g, '')}"`)
    fs.createReadStream(abs).pipe(res)
  })

  router.delete('/:projectId/tickets/:ticketId/attachments/:attachmentId', async (req: Request, res: Response) => {
    const parsed = parseTicketKey(req.params.ticketId as string)
    if (!parsed) {
      res.status(400).json({ error: 'Invalid ticketId' })
      return
    }
    const attachmentId = req.params.attachmentId as string
    try {
      const ok = await attachmentManager.delete({
        slug: ctx(req).project.slug,
        ticketKey: parsed.key,
        attachmentId,
        projectPath: parsed.isPending ? null : ctx(req).project.path,
      })
      if (!ok) {
        res.status(404).json({ error: 'Attachment not found' })
        return
      }
      res.status(204).end()
    } catch (err) {
      console.error('[project-router] attachment delete error:', err)
      res.status(500).json({ error: 'Delete failed' })
    }
  })

  router.delete('/:projectId/tickets/:ticketId/attachments', async (req: Request, res: Response) => {
    const parsed = parseTicketKey(req.params.ticketId as string)
    if (!parsed) {
      res.status(400).json({ error: 'Invalid ticketId' })
      return
    }
    try {
      await attachmentManager.deleteAll(ctx(req).project.slug, parsed.key)
      res.status(204).end()
    } catch (err) {
      console.error('[project-router] attachment bulk delete error:', err)
      res.status(500).json({ error: 'Bulk delete failed' })
    }
  })

  // ─── Terminals ───────────────────────────────────────────────────────────────

  function requireTerminalsEnabled(_req: Request, res: Response, next: NextFunction): void {
    if (!TERMINAL_PANEL_ENABLED) {
      res.status(404).json({ error: 'Terminal panel disabled' })
      return
    }
    next()
  }

  router.get('/:projectId/terminals', requireTerminalsEnabled, (req: Request, res: Response) => {
    const projectId = ctx(req).project.id
    const sessions = getTerminalManager().listForProject(projectId)
    res.json({ sessions, limit: TERMINAL_MAX_PER_PROJECT })
  })

  router.post('/:projectId/terminals', requireTerminalsEnabled, (req: Request, res: Response) => {
    const { cols, rows, name } = req.body ?? {}
    const project = ctx(req).project
    try {
      const meta = getTerminalManager().create(project.id, {
        cwd: project.path,
        cols: typeof cols === 'number' ? cols : undefined,
        rows: typeof rows === 'number' ? rows : undefined,
        name: typeof name === 'string' ? name : undefined,
      })
      res.status(201).json({ session: meta })
    } catch (err) {
      if (err instanceof TerminalLimitExceededError) {
        res.status(409).json({ error: 'terminal_limit_exceeded', limit: TERMINAL_MAX_PER_PROJECT })
        return
      }
      if (err instanceof TerminalNameInvalidError) {
        res.status(400).json({ error: 'terminal_name_invalid' })
        return
      }
      console.error('[project-router] terminal create error:', err)
      res.status(500).json({ error: 'Failed to create terminal' })
    }
  })

  router.patch('/:projectId/terminals/:id', requireTerminalsEnabled, (req: Request, res: Response) => {
    const { name } = req.body ?? {}
    if (typeof name !== 'string') {
      res.status(400).json({ error: 'name is required' })
      return
    }
    const projectId = ctx(req).project.id
    try {
      const meta = getTerminalManager().rename(projectId, req.params.id as string, name)
      res.json({ session: meta })
    } catch (err) {
      if (err instanceof TerminalNotFoundError) {
        res.status(404).json({ error: 'terminal_not_found' })
        return
      }
      if (err instanceof TerminalNameInvalidError) {
        res.status(400).json({ error: 'terminal_name_invalid' })
        return
      }
      console.error('[project-router] terminal rename error:', err)
      res.status(500).json({ error: 'Failed to rename terminal' })
    }
  })

  router.delete('/:projectId/terminals/:id', requireTerminalsEnabled, (req: Request, res: Response) => {
    const projectId = ctx(req).project.id
    const ok = getTerminalManager().kill(projectId, req.params.id as string)
    if (!ok) {
      res.status(404).json({ error: 'terminal_not_found' })
      return
    }
    res.json({ ok: true })
  })

  // ─── Project settings (pipeline telemetry) ───────────────────────────────────

  router.get('/:projectId/settings', (req: Request, res: Response) => {
    const settings = getProjectSettings(ctx(req).db)
    res.json(settings)
  })

  router.patch('/:projectId/settings', (req: Request, res: Response) => {
    const { pipelineTelemetryEnabled, orchestratorModel } = req.body ?? {}
    const patch: Parameters<typeof updateProjectSettings>[1] = {}
    if (pipelineTelemetryEnabled !== undefined) {
      patch.pipelineTelemetryEnabled = Boolean(pipelineTelemetryEnabled)
    }
    const VALID_MODELS = ['sonnet', 'opus', 'haiku']
    if (orchestratorModel !== undefined) {
      if (typeof orchestratorModel !== 'string' || !VALID_MODELS.includes(orchestratorModel)) {
        res.status(400).json({ error: `orchestratorModel must be one of: ${VALID_MODELS.join(', ')}` })
        return
      }
      patch.orchestratorModel = orchestratorModel
    }
    try {
      updateProjectSettings(ctx(req).db, patch)
      res.json({ ok: true, settings: getProjectSettings(ctx(req).db) })
    } catch (err) {
      console.error('[project-router] settings patch error:', err)
      res.status(500).json({ error: 'Failed to update settings' })
    }
  })

  // ─── Agent models ────────────────────────────────────────────────────────────

  router.get('/:projectId/agent-models', (req: Request, res: Response) => {
    const { project } = ctx(req)
    const agents = readAgentModels(project.path)
    res.json({ agents })
  })

  router.patch('/:projectId/agent-models', (req: Request, res: Response) => {
    const { project } = ctx(req)
    const { defaultModel, overrides } = req.body ?? {}

    // Validate defaultModel if provided
    if (defaultModel !== undefined) {
      if (typeof defaultModel !== 'string' || !(VALID_MODEL_ALIASES as readonly string[]).includes(defaultModel)) {
        res.status(400).json({ error: `Invalid model alias. Must be one of: ${VALID_MODEL_ALIASES.join(', ')}` }); return
      }
    }
    // Validate overrides map if provided
    if (overrides !== undefined) {
      if (typeof overrides !== 'object' || Array.isArray(overrides) || overrides === null) {
        res.status(400).json({ error: 'overrides must be an object' }); return
      }
      for (const [agentName, modelValue] of Object.entries(overrides)) {
        if (typeof modelValue !== 'string' || !(VALID_MODEL_ALIASES as readonly string[]).includes(modelValue)) {
          res.status(400).json({ error: `Invalid model alias for agent "${agentName}". Must be one of: ${VALID_MODEL_ALIASES.join(', ')}` }); return
        }
      }
    }

    const configDir = path.join(project.path, '.specrails')
    const configPath = path.join(configDir, 'install-config.yaml')

    // Read existing config or build default shape
    let existingConfig: Record<string, unknown> = {
      version: 1,
      provider: 'claude',
      tier: 'quick',
      agents: { selected: [], excluded: [] },
      models: { preset: 'balanced', defaults: { model: 'sonnet' }, overrides: {} },
      agent_teams: false,
    }

    if (fs.existsSync(configPath)) {
      try {
        const text = fs.readFileSync(configPath, 'utf-8')
        // Parse fields we care about from the existing config text
        const versionMatch = text.match(/^version:\s*(\d+)/m)
        const providerMatch = text.match(/^provider:\s*(\S+)/m)
        const tierMatch = text.match(/^tier:\s*(\S+)/m)
        const presetMatch = text.match(/preset:\s*(\S+)/)
        const agentTeamsMatch = text.match(/^agent_teams:\s*(\S+)/m)

        // Parse selected agents list
        const selectedMatch = text.match(/selected:\s*\[([^\]]*)\]/)
        const excludedMatch = text.match(/excluded:\s*\[([^\]]*)\]/)
        const parsedSelected = selectedMatch
          ? selectedMatch[1].split(',').map(s => s.trim()).filter(Boolean)
          : []
        const parsedExcluded = excludedMatch
          ? excludedMatch[1].split(',').map(s => s.trim()).filter(Boolean)
          : []

        // Parse existing overrides to merge
        const existingOverrides: Record<string, string> = {}
        const overridesBlockMatch = text.match(/overrides:([\s\S]*?)(?:\n\S|$)/)
        if (overridesBlockMatch) {
          const block = overridesBlockMatch[1]
          const overrideLines = block.match(/^ {2,}(\S+):\s*(\S+)/gm) ?? []
          for (const line of overrideLines) {
            const m = line.match(/^\s+(\S+):\s*(\S+)/)
            if (m) existingOverrides[m[1]] = m[2]
          }
        }

        existingConfig = {
          version: versionMatch ? parseInt(versionMatch[1], 10) : 1,
          provider: providerMatch ? providerMatch[1] : 'claude',
          tier: tierMatch ? tierMatch[1] : 'quick',
          agents: { selected: parsedSelected, excluded: parsedExcluded },
          models: {
            preset: presetMatch ? presetMatch[1] : 'balanced',
            defaults: { model: 'sonnet' },
            overrides: existingOverrides,
          },
          agent_teams: agentTeamsMatch ? agentTeamsMatch[1] === 'true' : false,
        }
      } catch {
        // use defaults
      }
    }

    // Merge new values into config
    const mergedModels = existingConfig.models as {
      preset: string
      defaults: { model: string }
      overrides: Record<string, string>
    }
    if (defaultModel !== undefined) {
      mergedModels.defaults = { model: defaultModel as ModelAlias }
    }
    if (overrides !== undefined) {
      mergedModels.overrides = overrides as Record<string, string>
    }
    existingConfig.models = mergedModels

    try {
      fs.mkdirSync(configDir, { recursive: true })
      const yaml = serializeInstallConfigYaml(existingConfig)
      fs.writeFileSync(configPath, yaml, 'utf-8')
      applyModelConfig(project.path)
      const agents = readAgentModels(project.path)
      res.json({ agents })
    } catch (err) {
      console.error('[project-router] agent-models patch error:', err)
      res.status(500).json({ error: `Failed to apply model config: ${err}` })
    }
  })

  // ─── Diagnostic export ───────────────────────────────────────────────────────

  router.get('/:projectId/jobs/:jobId/diagnostic', async (req: Request, res: Response) => {
    const { db } = ctx(req)
    const jobId = req.params.jobId as string

    const blob = getTelemetryBlob(db, jobId)
    if (!blob) {
      res.status(404).json({ error: 'No telemetry data for this job' })
      return
    }
    if (blob.state === 'expired') {
      res.status(410).json({ error: 'Telemetry data has been expired and is no longer available' })
      return
    }

    const job = getJob(db, jobId)
    if (!job) {
      res.status(404).json({ error: 'Job not found' })
      return
    }

    const summaries = getTelemetrySummaries(db, jobId)
    const events = getJobEvents(db, jobId)

    try {
      const dateStr = new Date().toISOString().slice(0, 10)
      const filename = `specrails-diagnostic-${jobId}-${dateStr}.zip`
      res.setHeader('Content-Type', 'application/zip')
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)

      await createDiagnosticZip(res, {
        job,
        blob,
        summaries,
        events,
      })
    } catch (err) {
      if (!res.headersSent) {
        console.error('[project-router] diagnostic export error:', err)
        res.status(500).json({ error: 'Failed to create diagnostic export' })
      }
    }
  })

  return router
}
